apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiremock-data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # MicroK8s usually has this as default; you can omit if default is fine
  storageClassName: microk8s-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      containers:
        - name: wiremock
          image: wiremock/wiremock:3.13.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # Optional: verbose logs + response templating
            - name: WIREMOCK_OPTIONS
              value: "--global-response-templating --verbose"
          volumeMounts:
            - name: wiremock-storage
              mountPath: /home/wiremock
          readinessProbe:
            httpGet:
              path: /__admin/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /__admin/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: wiremock-storage
          persistentVolumeClaim:
            claimName: wiremock-data
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app: wiremock
  ports:
    - port: 80
      targetPort: 8080
